dasvurl/grails-app/domain/com/dasvurl/WebRegister.groovy
package com.dasvurl

class WebRegister {

    String fullName
    String email
    String phoneNumber
    String gender
    String country1
    String country2
    String country3
    String course
    String intake

    Date dateCreated
    Date lastModified

    static constraints = {
        fullName(nullable: false, blank: false)
        email(nullable: false, blank: false)
        phoneNumber(nullable: false, blank: false)
        gender(nullable: false, blank: false)
        country1(nullable: false, blank: false)
        country2(nullable: false, blank: false)
        country3(nullable: false, blank: false)
        course(nullable: false, blank: false)
        intake(nullable: false, blank: false)
        dateCreated nullable: true, blank: true
        lastModified nullable: true, blank: true
    }
}

dasvurl/grails-app/controllers/com/dasvurl/WebRegisterViewController.groovy
package com.dasvurl

import grails.plugin.springsecurity.annotation.Secured

@Secured(value=["hasRole('USER')"])
class WebRegisterViewController {

    def index(Integer max){
        params.max = Math.min(max ?: 10, 100)
        respond WebRegister.list(params), model:[WebRegisterInstanceCount: RegisterForm.count()]
    }

    def show(WebRegister WebRegisterInstance) {
        respond WebRegisterInstance
    }
}

dasvurl/grails-app/views/webRegisterView/_form.gsp
<%@ page import="com.dasvurl.WebRegister" %>



<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'fullName', 'error')} required">
	<label for="fullName">
		<g:message code="webRegister.fullName.label" default="Full Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="fullName" required="" value="${webRegisterInstance?.fullName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="webRegister.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="email" required="" value="${webRegisterInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'phoneNumber', 'error')} required">
	<label for="phoneNumber">
		<g:message code="webRegister.phoneNumber.label" default="Phone Number" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="phoneNumber" required="" value="${webRegisterInstance?.phoneNumber}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'gender', 'error')} required">
	<label for="gender">
		<g:message code="webRegister.gender.label" default="Gender" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="gender" required="" value="${webRegisterInstance?.gender}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'country1', 'error')} required">
	<label for="country1">
		<g:message code="webRegister.country1.label" default="Country1" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="country1" required="" value="${webRegisterInstance?.country1}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'country2', 'error')} required">
	<label for="country2">
		<g:message code="webRegister.country2.label" default="Country2" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="country2" required="" value="${webRegisterInstance?.country2}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'country3', 'error')} required">
	<label for="country3">
		<g:message code="webRegister.country3.label" default="Country3" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="country3" required="" value="${webRegisterInstance?.country3}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'course', 'error')} required">
	<label for="course">
		<g:message code="webRegister.course.label" default="Course" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="course" required="" value="${webRegisterInstance?.course}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'intake', 'error')} required">
	<label for="intake">
		<g:message code="webRegister.intake.label" default="Intake" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="intake" required="" value="${webRegisterInstance?.intake}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: webRegisterInstance, field: 'lastModified', 'error')} ">
	<label for="lastModified">
		<g:message code="webRegister.lastModified.label" default="Last Modified" />
		
	</label>
	<g:datePicker name="lastModified" precision="day"  value="${webRegisterInstance?.lastModified}" default="none" noSelection="['': '']" />

</div>

dasvurl/grails-app/views/webRegisterView/_registerEmail.gsp
<%@ page contentType="text/html"%>
<%@ page import="com.dasvurl.WebRegister" %>
<div>
    Hi,
    There is a new Registration please assist quickly<br>
    <b>Name</b>: ${webRegister.fullName}<br>
    <b>email</b>: ${webRegister.email}<br>
    <b>Phone</b>: ${webRegister.phoneNumber}<br/>
    <b>Gender</b>: ${webRegister.gender}<br/>
    <emp><b>Country Preferences:</b></emp><br/>
    <b>Country1</b>: ${webRegister.country1}<br/>
    <b>Country2</b>: ${webRegister.country1}<br/>
    <b>Country3</b>: ${webRegister.country1}<br/>
    <br/>
    <b>course</b>: ${webRegister.course}<br/>
    <b>intake</b>: ${webRegister.intake}<br/>
    <b></b>
</div>

dasvurl/grails-app/views/webRegisterView/index.gsp
<%@ page import="com.dasvurl.WebRegister" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'webRegister.label', default: 'WebRegister')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-webRegister" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:form controller="logout"><g:submitButton name="Logout">Logout</g:submitButton></g:form></li>
			</ul>
		</div>
		<div id="list-webRegister" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="fullName" title="${message(code: 'webRegister.fullName.label', default: 'Full Name')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'webRegister.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="phoneNumber" title="${message(code: 'webRegister.phoneNumber.label', default: 'Phone Number')}" />
					
						<g:sortableColumn property="gender" title="${message(code: 'webRegister.gender.label', default: 'Gender')}" />
					
						<g:sortableColumn property="country1" title="${message(code: 'webRegister.country1.label', default: 'Country1')}" />
					
						<g:sortableColumn property="country2" title="${message(code: 'webRegister.country2.label', default: 'Country2')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${webRegisterInstanceList}" status="i" var="webRegisterInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${webRegisterInstance.id}">${fieldValue(bean: webRegisterInstance, field: "fullName")}</g:link></td>
					
						<td>${fieldValue(bean: webRegisterInstance, field: "email")}</td>
					
						<td>${fieldValue(bean: webRegisterInstance, field: "phoneNumber")}</td>
					
						<td>${fieldValue(bean: webRegisterInstance, field: "gender")}</td>
					
						<td>${fieldValue(bean: webRegisterInstance, field: "country1")}</td>
					
						<td>${fieldValue(bean: webRegisterInstance, field: "country2")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${webRegisterInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

dasvurl/grails-app/views/webRegisterView/show.gsp
<%@ page import="com.dasvurl.WebRegister" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'webRegister.label', default: 'WebRegister')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-webRegister" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-webRegister" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list webRegister">
			
				<g:if test="${webRegisterInstance?.fullName}">
				<li class="fieldcontain">
					<span id="fullName-label" class="property-label"><g:message code="webRegister.fullName.label" default="Full Name" /></span>
					
						<span class="property-value" aria-labelledby="fullName-label"><g:fieldValue bean="${webRegisterInstance}" field="fullName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="webRegister.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${webRegisterInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.phoneNumber}">
				<li class="fieldcontain">
					<span id="phoneNumber-label" class="property-label"><g:message code="webRegister.phoneNumber.label" default="Phone Number" /></span>
					
						<span class="property-value" aria-labelledby="phoneNumber-label"><g:fieldValue bean="${webRegisterInstance}" field="phoneNumber"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.gender}">
				<li class="fieldcontain">
					<span id="gender-label" class="property-label"><g:message code="webRegister.gender.label" default="Gender" /></span>
					
						<span class="property-value" aria-labelledby="gender-label"><g:fieldValue bean="${webRegisterInstance}" field="gender"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.country1}">
				<li class="fieldcontain">
					<span id="country1-label" class="property-label"><g:message code="webRegister.country1.label" default="Country1" /></span>
					
						<span class="property-value" aria-labelledby="country1-label"><g:fieldValue bean="${webRegisterInstance}" field="country1"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.country2}">
				<li class="fieldcontain">
					<span id="country2-label" class="property-label"><g:message code="webRegister.country2.label" default="Country2" /></span>
					
						<span class="property-value" aria-labelledby="country2-label"><g:fieldValue bean="${webRegisterInstance}" field="country2"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.country3}">
				<li class="fieldcontain">
					<span id="country3-label" class="property-label"><g:message code="webRegister.country3.label" default="Country3" /></span>
					
						<span class="property-value" aria-labelledby="country3-label"><g:fieldValue bean="${webRegisterInstance}" field="country3"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.course}">
				<li class="fieldcontain">
					<span id="course-label" class="property-label"><g:message code="webRegister.course.label" default="Course" /></span>
					
						<span class="property-value" aria-labelledby="course-label"><g:fieldValue bean="${webRegisterInstance}" field="course"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.intake}">
				<li class="fieldcontain">
					<span id="intake-label" class="property-label"><g:message code="webRegister.intake.label" default="Intake" /></span>
					
						<span class="property-value" aria-labelledby="intake-label"><g:fieldValue bean="${webRegisterInstance}" field="intake"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="webRegister.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${webRegisterInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${webRegisterInstance?.lastModified}">
				<li class="fieldcontain">
					<span id="lastModified-label" class="property-label"><g:message code="webRegister.lastModified.label" default="Last Modified" /></span>
					
						<span class="property-value" aria-labelledby="lastModified-label"><g:formatDate date="${webRegisterInstance?.lastModified}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			%{--<g:form url="[resource:webRegisterInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${webRegisterInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>--}%
		</div>
	</body>
</html>