dasvurl/grails-app/controllers/com/dasvurl/RegisterFormController.groovy
package com.dasvurl

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured(value=["hasRole('USER')"])
@Transactional(readOnly = true)
class RegisterFormController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond RegisterForm.list(params), model:[registerFormInstanceCount: RegisterForm.count()]
    }

    def show(RegisterForm registerFormInstance) {
        respond registerFormInstance
    }

    def create() {
        respond new RegisterForm(params)
    }

    @Transactional
    def save(RegisterForm registerFormInstance) {
        if (registerFormInstance == null) {
            notFound()
            return
        }

        if (registerFormInstance.hasErrors()) {
            respond registerFormInstance.errors, view:'create'
            return
        }

        registerFormInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'registerForm.label', default: 'RegisterForm'), registerFormInstance.id])
                redirect registerFormInstance
            }
            '*' { respond registerFormInstance, [status: CREATED] }
        }
    }

    @Secured(value=["hasRole('USER')"])
    def edit(RegisterForm registerFormInstance) {
        respond registerFormInstance
    }

    @Secured(value=["hasRole('USER')"])
    @Transactional
    def update(RegisterForm registerFormInstance) {
        if (registerFormInstance == null) {
            notFound()
            return
        }

        if (registerFormInstance.hasErrors()) {
            respond registerFormInstance.errors, view:'edit'
            return
        }

        registerFormInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'RegisterForm.label', default: 'RegisterForm'), registerFormInstance.id])
                redirect registerFormInstance
            }
            '*'{ respond registerFormInstance, [status: OK] }
        }
    }

    @Secured(value=["hasRole('USER')"])
    @Transactional
    def delete(RegisterForm registerFormInstance) {

        if (registerFormInstance == null) {
            notFound()
            return
        }

        registerFormInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'RegisterForm.label', default: 'RegisterForm'), registerFormInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'registerForm.label', default: 'RegisterForm'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

dasvurl/grails-app/views/registerForm/_form.gsp
<%@ page import="com.dasvurl.RegisterForm" %>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'toldName', 'error')} required">
	<label for="toldName">
		<g:message code="registerForm.toldName.label" default="Told Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="toldName" required="" value="${registerFormInstance?.toldName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="registerForm.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" required="" value="${registerFormInstance?.lastName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'dateOfBirth', 'error')} required">
	<label for="dateOfBirth">
		<g:message code="registerForm.dateOfBirth.label" default="Date Of Birth" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="dateOfBirth" precision="day"  value="${registerFormInstance?.dateOfBirth}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'gender', 'error')} required">
	<label for="gender">
		<g:message code="registerForm.gender.label" default="Gender" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="gender" from="${registerFormInstance.constraints.gender.inList}" required="" value="${registerFormInstance?.gender}" valueMessagePrefix="registerForm.gender"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'age', 'error')} required">
	<label for="age">
		<g:message code="registerForm.age.label" default="Age" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="age" maxlength="3" required="" value="${registerFormInstance?.age}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="registerForm.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="email" required="" value="${registerFormInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'address', 'error')} required">
	<label for="address">
		<g:message code="registerForm.address.label" default="Address" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="address" required="" value="${registerFormInstance?.address}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'correspondingAddress', 'error')} required">
	<label for="correspondingAddress">
		<g:message code="registerForm.correspondingAddress.label" default="Corresponding Address" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="correspondingAddress" required="" value="${registerFormInstance?.correspondingAddress}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'mobileNo', 'error')} required">
	<label for="mobileNo">
		<g:message code="registerForm.mobileNo.label" default="Mobile No" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="mobileNo" maxlength="12" required="" value="${registerFormInstance?.mobileNo}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'landlineNo', 'error')} required">
	<label for="landlineNo">
		<g:message code="registerForm.landlineNo.label" default="Landline No" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="landlineNo" required="" value="${registerFormInstance?.landlineNo}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'qualification', 'error')} required">
	<label for="qualification">
		<g:message code="registerForm.qualification.label" default="Qualification" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="qualification" required="" value="${registerFormInstance?.qualification}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'currentEducationStatus', 'error')} required">
	<label for="currentEducationStatus">
		<g:message code="registerForm.currentEducationStatus.label" default="Current Education Status" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="currentEducationStatus" required="" value="${registerFormInstance?.currentEducationStatus}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'schoolName', 'error')} required">
	<label for="schoolName">
		<g:message code="registerForm.schoolName.label" default="School Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="schoolName" required="" value="${registerFormInstance?.schoolName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'universityName', 'error')} required">
	<label for="universityName">
		<g:message code="registerForm.universityName.label" default="University Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="universityName" required="" value="${registerFormInstance?.universityName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'passport', 'error')} ">
	<label for="passport">
		<g:message code="registerForm.passport.label" default="Passport" />
		
	</label>
	<g:checkBox name="passport" value="${registerFormInstance?.passport}" />

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'interestedInStudying', 'error')} required">
	<label for="interestedInStudying">
		<g:message code="registerForm.interestedInStudying.label" default="Interested In Studying" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="interestedInStudying" required="" value="${registerFormInstance?.interestedInStudying}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: registerFormInstance, field: 'countryPreference', 'error')} required">
	<label for="countryPreference">
		<g:message code="registerForm.countryPreference.label" default="Country Preference" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="countryPreference" required="" value="${registerFormInstance?.countryPreference}"/>

</div>

dasvurl/grails-app/views/registerForm/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'registerForm.label', default: 'RegisterForm')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-registerForm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<sec:ifAnyGranted roles='USER'>
					<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
					<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
					<li><g:form controller="logout"><g:submitButton name="Logout">Logout</g:submitButton></g:form></li>
				</sec:ifAnyGranted>
				<sec:ifNotLoggedIn>
					<li><g:link class="list" controller="login"><g:message code="default.login" default="Login"/></g:link></li>
				</sec:ifNotLoggedIn>
			</ul>
		</div>
		<div id="create-registerForm" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${registerFormInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${registerFormInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:registerFormInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

dasvurl/grails-app/views/registerForm/edit.gsp
<%@ page import="com.dasvurl.RegisterForm" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'registerForm.label', default: 'RegisterForm')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-registerForm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-registerForm" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${registerFormInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${registerFormInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:registerFormInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${registerFormInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

dasvurl/grails-app/views/registerForm/index.gsp
<%@ page import="com.dasvurl.RegisterForm" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'registerForm.label', default: 'RegisterForm')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-registerForm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:form controller="logout"><g:submitButton name="Logout">Logout</g:submitButton></g:form></li>
			</ul>
		</div>
		<div id="list-registerForm" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="mobileNo" title="${message(code: 'registerForm.mobileNo.label', default: 'Mobile No')}" />
					
						<g:sortableColumn property="age" title="${message(code: 'registerForm.age.label', default: 'Age')}" />
					
						<g:sortableColumn property="gender" title="${message(code: 'registerForm.gender.label', default: 'Gender')}" />
					
						<g:sortableColumn property="address" title="${message(code: 'registerForm.address.label', default: 'Address')}" />
					
						<g:sortableColumn property="correspondingAddress" title="${message(code: 'registerForm.correspondingAddress.label', default: 'Corresponding Address')}" />
					
						<g:sortableColumn property="currentEducationStatus" title="${message(code: 'registerForm.currentEducationStatus.label', default: 'Current Education Status')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${registerFormInstanceList}" status="i" var="registerFormInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${registerFormInstance.id}">${fieldValue(bean: registerFormInstance, field: "mobileNo")}</g:link></td>
					
						<td>${fieldValue(bean: registerFormInstance, field: "age")}</td>
					
						<td>${fieldValue(bean: registerFormInstance, field: "gender")}</td>
					
						<td>${fieldValue(bean: registerFormInstance, field: "address")}</td>
					
						<td>${fieldValue(bean: registerFormInstance, field: "correspondingAddress")}</td>
					
						<td>${fieldValue(bean: registerFormInstance, field: "currentEducationStatus")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${registerFormInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

dasvurl/grails-app/views/registerForm/show.gsp
<%@ page import="com.dasvurl.RegisterForm" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'registerForm.label', default: 'RegisterForm')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-registerForm" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<sec:ifAnyGranted roles='user'>
					<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
					<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				</sec:ifAnyGranted>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li><g:link class="list" controller="login"><g:message code="default.login" default="Login"/></g:link></li>
			</ul>
		</div>
		<div id="show-registerForm" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list registerForm">

				<g:if test="${registerFormInstance?.toldName}">
					<li class="fieldcontain">
						<span id="toldName-label" class="property-label"><g:message code="registerForm.toldName.label" default="Told Name" /></span>

						<span class="property-value" aria-labelledby="toldName-label"><g:fieldValue bean="${registerFormInstance}" field="toldName"/></span>

					</li>
				</g:if>

				<g:if test="${registerFormInstance?.lastName}">
					<li class="fieldcontain">
						<span id="lastName-label" class="property-label"><g:message code="registerForm.lastName.label" default="Last Name" /></span>

						<span class="property-value" aria-labelledby="lastName-label"><g:fieldValue bean="${registerFormInstance}" field="lastName"/></span>

					</li>
				</g:if>

				<g:if test="${registerFormInstance?.mobileNo}">
				<li class="fieldcontain">
					<span id="mobileNo-label" class="property-label"><g:message code="registerForm.mobileNo.label" default="Mobile No" /></span>
					
						<span class="property-value" aria-labelledby="mobileNo-label"><g:fieldValue bean="${registerFormInstance}" field="mobileNo"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.age}">
				<li class="fieldcontain">
					<span id="age-label" class="property-label"><g:message code="registerForm.age.label" default="Age" /></span>
					
						<span class="property-value" aria-labelledby="age-label"><g:fieldValue bean="${registerFormInstance}" field="age"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.gender}">
				<li class="fieldcontain">
					<span id="gender-label" class="property-label"><g:message code="registerForm.gender.label" default="Gender" /></span>
					
						<span class="property-value" aria-labelledby="gender-label"><g:fieldValue bean="${registerFormInstance}" field="gender"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.address}">
				<li class="fieldcontain">
					<span id="address-label" class="property-label"><g:message code="registerForm.address.label" default="Address" /></span>
					
						<span class="property-value" aria-labelledby="address-label"><g:fieldValue bean="${registerFormInstance}" field="address"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.correspondingAddress}">
				<li class="fieldcontain">
					<span id="correspondingAddress-label" class="property-label"><g:message code="registerForm.correspondingAddress.label" default="Corresponding Address" /></span>
					
						<span class="property-value" aria-labelledby="correspondingAddress-label"><g:fieldValue bean="${registerFormInstance}" field="correspondingAddress"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.currentEducationStatus}">
				<li class="fieldcontain">
					<span id="currentEducationStatus-label" class="property-label"><g:message code="registerForm.currentEducationStatus.label" default="Current Education Status" /></span>
					
						<span class="property-value" aria-labelledby="currentEducationStatus-label"><g:fieldValue bean="${registerFormInstance}" field="currentEducationStatus"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.dateOfBirth}">
				<li class="fieldcontain">
					<span id="dateOfBirth-label" class="property-label"><g:message code="registerForm.dateOfBirth.label" default="Date Of Birth" /></span>
					
						<span class="property-value" aria-labelledby="dateOfBirth-label"><g:formatDate date="${registerFormInstance?.dateOfBirth}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="registerForm.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${registerFormInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.landlineNo}">
				<li class="fieldcontain">
					<span id="landlineNo-label" class="property-label"><g:message code="registerForm.landlineNo.label" default="Landline No" /></span>
					
						<span class="property-value" aria-labelledby="landlineNo-label"><g:fieldValue bean="${registerFormInstance}" field="landlineNo"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.passport}">
				<li class="fieldcontain">
					<span id="passport-label" class="property-label"><g:message code="registerForm.passport.label" default="Passport" /></span>
					
						<span class="property-value" aria-labelledby="passport-label"><g:formatBoolean boolean="${registerFormInstance?.passport}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.qualification}">
				<li class="fieldcontain">
					<span id="qualification-label" class="property-label"><g:message code="registerForm.qualification.label" default="Qualification" /></span>
					
						<span class="property-value" aria-labelledby="qualification-label"><g:fieldValue bean="${registerFormInstance}" field="qualification"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${registerFormInstance?.schoolName}">
				<li class="fieldcontain">
					<span id="schoolName-label" class="property-label"><g:message code="registerForm.schoolName.label" default="School Name" /></span>
					
						<span class="property-value" aria-labelledby="schoolName-label"><g:fieldValue bean="${registerFormInstance}" field="schoolName"/></span>
					
				</li>
				</g:if>

				<g:if test="${registerFormInstance?.universityName}">
				<li class="fieldcontain">
					<span id="universityName-label" class="property-label"><g:message code="registerForm.universityName.label" default="University Name" /></span>
					
						<span class="property-value" aria-labelledby="universityName-label"><g:fieldValue bean="${registerFormInstance}" field="universityName"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:registerFormInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<sec:ifAnyGranted roles='user'>
						<g:link class="edit" action="edit" resource="${registerFormInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
						<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
					</sec:ifAnyGranted>
					<a onclick="window.print()">Print</a>
				</fieldset>
			</g:form>
		</div>
	</body>
</html>